# Generated by Django 4.2.5 on 2023-09-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='作者')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='机构')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='标题')),
                ('year', models.SmallIntegerField(blank=True, verbose_name='年份')),
                ('journal', models.CharField(blank=True, max_length=255, verbose_name='期刊')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='doi')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('pdf_url', models.CharField(blank=True, max_length=255, verbose_name='pdf下载地址')),
                ('file_url', models.CharField(blank=True, max_length=255, verbose_name='pdf本地地址')),
            ],
            options={
                'verbose_name': '论文信息',
                'indexes': [models.Index(fields=['doi', 'journal'], name='idx_paper')],
            },
        ),
    ]
