# Generated by Django 4.2.5 on 2023-09-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='track',
            field=models.CharField(blank=True, max_length=255, verbose_name='track'),
        ),
    ]
